# These are supported funding model platforms

github: brandonroberts # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ['https://brandonroberts.dev', 'https://twitch.tv/brandontroberts'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
